imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*, myreport.html/*]

tools:
    # Some Metrics + Bug Detection/Auto-Fixes
    php_analyzer: true
    php_code_sniffer: true

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.0
    tests:
        override:
            -
                command: "make test"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
